### ISSUE TITLE
Check google analytics setup

### ISSUE THREAD

**Issue by ColinEberhardt** [beautify/beautify-site#41]

**Comment by ChrisGrant** [comment]
What do we want to do here? Do we just want tracking of when someone clicks the download button?

This is all we have so far at the top of each page:

  <script type="text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','http://www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-262131-5', 'beautify.io');
    ga('send', 'pageview');
  </script>

**Comment by godds** [comment]
Could we set the download button up as a "goal" (to track it as a "conversion")?

Ideally we'd also track the other interactive bits on the download page so that we can see which themes people are picking, etc.  Maybe that could be info that's hooked into the "goal" somehow?  (I don't really know GA)
